/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkopengl_NdkGlRender */

#ifndef _Included_com_example_ndkopengl_NdkGlRender
#define _Included_com_example_ndkopengl_NdkGlRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkopengl_NdkGlRender
 * Method:    onNdkSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkopengl_NdkGlRender_onNdkSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndkopengl_NdkGlRender
 * Method:    onNdkDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkopengl_NdkGlRender_onNdkDrawFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndkopengl_NdkGlRender
 * Method:    onNdkSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_ndkopengl_NdkGlRender_onNdkSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
